apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-deploy
  labels:
    app: mobile-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile-app
  template:
    metadata:
      labels:
        app: mobile-app
    spec:
      containers:
      - name: mobile-cont
        image: rupen04/mobile-frontend:1.0
        ports:
        - containerPort: 80
